let tours = [
    {
        "id":1,
        "image":"img/prague_1.jpg",
        "caption":"My fabulous Prague",
        "days":"4",
        "moves":"2",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"145 Euro",
    },
    {
        "id":2,
        "image":"img/prague_4.jpg",
        "caption":"Prague is my favorite city",
        "days":"4",
        "moves":"2",
        "towns":"Krakow, Prague, Dresden",
        "price":"180 Euro",
    },
    {
        "id":3,
        "image":"img/prague_5.jpg",
        "caption":"Bohemian weekend ",
        "days":"4",
        "moves":"no",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"340 Euro",
    },
    {
        "id":4,
        "image":"img/vienna_2.jpg",
        "caption":"Weekend in Europe",
        "days":"5",
        "moves":"no",
        "towns":"Krakow, Prague, Vienna, Budapest",
        "price":"250 Euro",
    },
    {
        "id":5,
        "image":"img/karlovy_vary_2.jpg",
        "caption":"Czech fairy tales",
        "days":"6",
        "moves":"2",
        "towns":"Prague, Karlovy Vary",
        "price":"220 Euro",
    },
    {
        "id":6,
        "image":"img/dresden_2.jpg",
        "caption":"Czech pearls",
        "days":"5",
        "moves":"no",
        "towns":"Dresden, Prague, Karlovy Vary",
        "price":"330 Euro",
    }
]