let tours = [
    {
        "id":1,
        "image":"img/vienna_3.jpg",
        "caption":"Luxury weekend",
        "days":"3",
        "moves":"no",
        "countries":"Poland, Austria, Hungary",
        "towns":"Krakow, Vienna, Budapest",
        "price":"165 Euro",
    },
    {
        "id":2,
        "image":"img/salzburg_1.jpg",
        "caption":"Austrian weekend",
        "days":"4",
        "moves":"no",
        "countries":"Austria, Czechia",
        "towns":"Vienna, Salzburg, Prague ",
        "price":"224 Euro",
    },
    {
        "id":3,
        "image":"img/salzburg_2.jpg",
        "caption":"A paradise corner of Austria",
        "days":"6",
        "moves":"2",
        "countries":"Austria, Poland",
        "towns":"Vienna, Salzburg, Krakow",
        "price":"260 Euro",
    },
    {
        "id":4,
        "image":"img/hallstatt_1.jpg",
        "caption":"Beauty without filters",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Austria",
        "towns":"Krakow, Salzburg, Hallstatt",
        "price":"290 Euro",
    },
    {
        "id":5,
        "image":"img/ljubljana_2.jpeg",
        "caption":"Alpine luxury",
        "days":"5",
        "moves":"no",
        "countries":"Hungary, Austria, Slovenia",
        "towns":"Budapest, Salzburg, Ljubljana",
        "price":"300 Euro",
    },
    {
        "id":6,
        "image":"img/munich_2.jpg",
        "caption":"The best of the best",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Austria, Germany",
        "towns":"Krakow, Vienna, Munich",
        "price":"255 Euro",
    }
]