let tours = [
    {
        "id":1,
        "image":"img/berlin_1.jpg",
        "caption":"In the footsteps of secrets and legends",
        "days":"4",
        "moves":"1",
        "countries":"Poland, Germany",
        "towns":"Wroclaw, Berlin, Dresden",
        "price":"180 Euro",
    },
    {
        "id":2,
        "image":"img/berlin_2.jpeg",
        "caption":"Berlin and Dresden",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Germany",
        "towns":"Krakow, Berlin, Dresden",
        "price":"185 Euro",
    },
    {
        "id":3,
        "image":"img/dresden_3.jpg",
        "caption":"European trio",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Germany",
        "towns":"Krakow, Berlin, Dresden",
        "price":"180 Euro",
    },
    {
        "id":4,
        "image":"img/munich_1.jpg",
        "caption":"Alpine pearls",
        "days":"6",
        "moves":"no",
        "countries":"Germany, Austria",
        "towns":"Munich, Salzburg, Hallstatt",
        "price":"300 Euro",
    },
    {
        "id":5,
        "image":"img/hamburg_1.jpg",
        "caption":"Unforgettable vacation",
        "days":"6",
        "moves":"no",
        "countries":"Germany",
        "towns":"Berlin, Dresden, Hamburg",
        "price":"330 Euro",
    },
    {
        "id":6,
        "image":"img/paris_5.jpg",
        "caption":"Paris and Berlin",
        "days":"5",
        "moves":"2",
        "countries":"Germany, France, Czechia",
        "towns":"Berlin, Paris, Prague",
        "price":"250 Euro",
    }
]