let tours = [
    {
        "id":1,
        "image":"img/tallin_1.jpg",
        "caption":"By the waves of the Baltic Sea",
        "days":"6",
        "moves":"no",
        "towns":"Tallinn, Helsinki, Stockholm",
        "price":"325 Euro",
    },
    {
        "id":2,
        "image":"img/stockholm_3.jpg",
        "caption":"Welcome to Stockholm",
        "days":"6",
        "moves":"no",
        "towns":"Riga, Tallinn, Stockholm",
        "price":"345 Euro",
    },
    {
        "id":3,
        "image":"img/stockholm_1.jpg",
        "caption":"Stockholm and Oslo",
        "days":"7",
        "moves":"no",
        "towns":"Stockholm, Oslo, Riga",
        "price":"450 Euro",
    },
    {
        "id":4,
        "image":"img/copenhagen_2.jpg",
        "caption":"Secrets of the North",
        "days":"7",
        "moves":"no",
        "towns":"Stockholm, Copenhagen, Hamburg",
        "price":"490 Euro",
    },
    {
        "id":5,
        "image":"img/copenhagen_1.jpg",
        "caption":"Cities of the northern winds",
        "days":"10",
        "moves":"no",
        "towns":"Oslo, Copenhagen, Stockholm",
        "price":"620 Euro",
    },
    {
        "id":6,
        "image":"img/residense.jpg",
        "caption":"Journey to Santa's world",
        "days":"9",
        "moves":"no",
        "towns":"Tallinn, Helsinki, Stockholm",
        "price":"750 Euro",
    }   
]