let tours = [
    {
        "id":1,
        "image":"img/castle_2.jpg",
        "caption":"Weekend in Transylvania",
        "days":"4",
        "moves":"2",
        "towns":"Bushten, Brasov",
        "price":"130 Euro",
    },
    {
        "id":2,
        "image":"img/castle_3.jpeg",
        "caption":"Mystical Transylvania",
        "days":"3",
        "moves":"no",
        "towns":"Bushten, Brasov",
        "price":"160 Euro",
    },
    {
        "id":3,
        "image":"img/bucharest_2.jpg",
        "caption":"Bucharest and castles of Transylvania",
        "days":"4",
        "moves":"1",
        "towns":"Bucharest, Brasov",
        "price":"170 Euro",
    },
    {
        "id":4,
        "image":"img/athens_1.jpg",
        "caption":"Legends and myths of ancient Greece",
        "days":"6",
        "moves":"2",
        "towns":"Athens, Bucharest, Brasov",
        "price":"290 Euro",
    },
    {
        "id":5,
        "image":"img/istanbul_1.jpg",
        "caption":"From Istanbul to Athens",
        "days":"6",
        "moves":"2",
        "towns":"Athens, Istanbul, Bucharest",
        "price":"290 Euro",
    },
    {
        "id":6,
        "image":"img/timisoara.jpg",
        "caption":"A trip through the Balkans",
        "days":"6",
        "moves":"2",
        "towns":"Dubrovnik, Budva, Timisoara",
        "price":"290 Euro",
    }
]