let tours = [
    {
        "id":1,
        "image":"img/vienna_3.jpg",
        "caption":"Luxury weekend",
        "days":"3",
        "moves":"no",
        "countries":"Poland, Austria, Hungary",
        "towns":"Krakow, Vienna, Budapest",
        "price":"165 Euro",
    },
    {
        "id":3,
        "image":"img/flam_1.jpg",
        "caption":"Getting to know Norway",
        "days":"7",
        "moves":"2",
        "countries":"Denmark, Norway",
        "towns":"Copenhagen, Flam, Bergen",
        "price":"410 Euro",
    },
    {
        "id":2,
        "image":"img/rome_1.jpg",
        "caption":"Weekend in Italy",
        "days":"5",
        "moves":"2",
        "countries":"Italy",
        "towns":"Venice, Florence, Rome",
        "price":"237 Euro",
    },
 
    {
        "id":4,
        "image":"img/paris_1.jpg",
        "caption":"Paris and Amsterdam",
        "days":"7",
        "moves":"no",
        "countries":"Germany, Netherlands, France",
        "towns":"Berlin, Amsterdam, Paris",
        "price":"427 Euro",
    },
    {
        "id":5,
        "image":"img/dresden_3.jpg",
        "caption":"European trio",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Germany",
        "towns":"Krakow, Berlin, Dresden",
        "price":"180 Euro",
    },
    {
        "id":6,
        "image":"img/oslo_1.jpg",
        "caption":"Land of fjords and glaciers",
        "days":"7",
        "moves":"no",
        "countries":"Denmark, Norway",
        "towns":"Copenhagen, Oslo, Bergen",
        "price":"510 Euro",
    },
    {
        "id":7,
        "image":"img/prague_5.jpg",
        "caption":"Bohemian weekend ",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Czechia",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"340 Euro",
    },
    {
        "id":9,
        "image":"img/paris_4.jpg",
        "caption":"Wonderful vacion in France",
        "days":"7",
        "moves":"2",
        "countries":"Germany, France, Czechia",
        "towns":"Berlin, Paris, Prague",
        "price":"305 Euro",
    },
    {
        "id":8,
        "image":"img/castle_2.jpg",
        "caption":"Weekend in Transylvania",
        "days":"4",
        "moves":"2",
        "countries":"Romania",
        "towns":"Bushten, Brasov",
        "price":"130 Euro",
    },
    {
        "id":10,
        "image":"img/stockholm_1.jpg",
        "caption":"Stockholm and Oslo",
        "days":"7",
        "moves":"no",
        "countries":"Sweden, Norway, Latvia",
        "towns":"Stockholm, Oslo, Riga",
        "price":"450 Euro",
    },
    {
        "id":11,
        "image":"img/krakow_2.jpg",
        "caption":"Weekend in Krakow",
        "days":"3",
        "moves":"1",
        "countries":"Poland",
        "towns":"Krakow, Zakopane, Wieliczka",
        "price":"85 Euro",
    },
    {
        "id":12,
        "image":"img/salzburg_2.jpg",
        "caption":"A paradise corner of Austria",
        "days":"6",
        "moves":"2",
        "countries":"Austria, Poland",
        "towns":"Vienna, Salzburg, Krakow",
        "price":"260 Euro",
    },
    {
        "id":13,
        "image":"img/salzburg_1.jpg",
        "caption":"Austrian weekend",
        "days":"4",
        "moves":"no",
        "countries":"Austria, Czechia",
        "towns":"Vienna, Salzburg, Prague ",
        "price":"224 Euro",
    },
    {
        "id":14,
        "image":"img/prague_1.jpg",
        "caption":"My fabulous Prague",
        "days":"4",
        "moves":"2",
        "countries":"Poland, Czechia",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"145 Euro",
    },
    {
        "id":15,
        "image":"img/lucerne_2.jpg",
        "caption":"Weekend in Switzerland",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Switzerland",
        "towns":"Krakow, Lucerne, Zurich",
        "price":"276 Euro",
    },
    {
        "id":16,
        "image":"img/ljubljana_1.jpg",
        "caption":"Slovenia and Hungary",
        "days":"5",
        "moves":"2",
        "countries":"Hungary, Slovenia",
        "towns":"Budapest, Ljubljana",
        "price":"250 Euro",
    },
    {
        "id":17,
        "image":"img/paris_3.jpg",
        "caption":"Paris - the city of love",
        "days":"6",
        "moves":"2",
        "countries":"Poland, France, Czechia",
        "towns":"Krakow, Paris, Prague",
        "price":"295 Euro",
    },
    {
        "id":18,
        "image":"img/hallstatt_1.jpg",
        "caption":"Beauty without filters",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Austria",
        "towns":"Krakow, Salzburg, Hallstatt",
        "price":"290 Euro",
    },
    {
        "id":19,
        "image":"img/ljubljana_2.jpeg",
        "caption":"Alpine luxury",
        "days":"5",
        "moves":"no",
        "countries":"Hungary, Austria, Slovenia",
        "towns":"Budapest, Salzburg, Ljubljana",
        "price":"300 Euro",
    },
    {
        "id":20,
        "image":"img/warsaw_1.jpg",
        "caption":"Fairytale cities",
        "days":"8",
        "moves":"no",
        "countries":"Poland, Netherlands, France",
        "towns":"Warsaw, Amsterdam, Paris",
        "price":"460 Euro",
    },
    {
        "id":21,
        "image":"img/stockholm_3.jpg",
        "caption":"Welcome to Stockholm",
        "days":"6",
        "moves":"no",
        "countries":"Latvia, Estonia, Sweden",
        "towns":"Riga, Tallinn, Stockholm",
        "price":"345 Euro",
    },
    {
        "id":22,
        "image":"img/munich_2.jpg",
        "caption":"The best of the best",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Austria, Germany",
        "towns":"Krakow, Vienna, Munich",
        "price":"255 Euro",
    },
    {
        "id":23,
        "image":"img/zurich_1.jpg",
        "caption":"Beautiful days in Switzerland",
        "days":"5",
        "moves":"2",
        "countries":"Hungary, Autria, Switzerland",
        "towns":"Budapest, Vienna, Zurich",
        "price":"250 Euro",
    },
    {
        "id":24,
        "image":"img/castle_3.jpeg",
        "caption":"Mystical Transylvania",
        "days":"3",
        "moves":"no",
        "countries":"Romania",
        "towns":"Bushten, Brasov",
        "price":"160 Euro",
    },
    {
        "id":25,
        "image":"img/zurich_2.jpg",
        "caption":"Incredible Switzerland and Alsace",
        "days":"5",
        "moves":"no",
        "countries":"Austria, Switzerland",
        "towns":"Salzburg, Lucerne, Zurich",
        "price":"345 Euro",
    },
    {
        "id":26,
        "image":"img/prague_2.jpg",
        "caption":"Weekend in Europe",
        "days":"4",
        "moves":"1",
        "countries":"Poland, Czechia, Austria",
        "towns":"Krakow, Prague, Vienna",
        "price":"168 Euro",
    },
    {
        "id":27,
        "image":"img/luxembourg_1.jpg",
        "caption":"Paris and Luxembourg",
        "days":"6",
        "moves":"no",
        "countries":"Poland, France, Luxembourg",
        "towns":"Krakow, Paris, Luxembourg",
        "price":"380 Euro",
    },
    {
        "id":29,
        "image":"img/rome_2.jpg",
        "caption":"Rome: the Eternal city",
        "days":"6",
        "moves":"no",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Florence, Rome",
        "price":"355 Euro",
    },
    {
        "id":30,
        "image":"img/warsaw.png",
        "caption":"Krakow and Warsaw",
        "days":"3",
        "moves":"no",
        "countries":"Poland",
        "towns":"Krakow, Warsaw",
        "price":"130 Euro",
    },
    {
        "id":31,
        "image":"img/rouen_1.jpg",
        "caption":"Paris and Normandy",
        "days":"7",
        "moves":"no",
        "countries":"France, Poland",
        "towns":"Paris, Rouen, Krakow",
        "price":"410 Euro",
    },
    {
        "id":32,
        "image":"img/berlin_2.jpeg",
        "caption":"Berlin and Dresden",
        "days":"4",
        "moves":"no",
        "countries":"Poland, Germany",
        "towns":"Krakow, Berlin, Dresden",
        "price":"185 Euro",
    },
    {
        "id":33,
        "image":"img/lucerne_1.jpg",
        "caption":"Wonderful days in Switzerland",
        "days":"5",
        "moves":"2",
        "countries":"Austria, Switzerland",
        "towns":"Vienna, Lucerne, Zurich",
        "price":"235 Euro",
    },
    {
        "id":34,
        "image":"img/bucharest_2.jpg",
        "caption":"Castles of Transylvania",
        "days":"4",
        "moves":"1",
        "countries":"Romania",
        "towns":"Bucharest, Brasov",
        "price":"170 Euro",
    },
    {
        "id":35,
        "image":"img/eger_1.jpg",
        "caption":"Austrian hit and Budapest",
        "days":"4",
        "moves":"2",
        "countries":"Austria, Hungary",
        "towns":"Vienna, Budapest, Eger",
        "price":"156 Euro",
    },
    {
        "id":36,
        "image":"img/italy_1.jpg",
        "caption":"Weekend in Liguria",
        "days":"5",
        "moves":"2",
        "countries":"Italy",
        "towns":"Genoa, Florence, Cinque Terre",
        "price":"221 Euro",
    },
    {
        "id":37,
        "image":"img/berlin_1.jpg",
        "caption":"In the footsteps of legends",
        "days":"4",
        "moves":"1",
        "countries":"Poland, Germany",
        "towns":"Wroclaw, Berlin, Dresden",
        "price":"180 Euro",
    },
    {
        "id":38,
        "image":"img/tallin_1.jpg",
        "caption":"By the waves of the Baltic Sea",
        "days":"6",
        "moves":"no",
        "countries":"Estonia, Finland, Sweden",
        "towns":"Tallinn, Helsinki, Stockholm",
        "price":"325 Euro",
    },
    {
        "id":39,
        "image":"img/dresden_1.jpg",
        "caption":"Vacation in the Netherlands",
        "days":"7",
        "moves":"no",
        "countries":"Germany, Netherlands",
        "towns":"Dresden, Amsterdam, Cologne",
        "price":"375 Euro",
    },
    {
        "id":40,
        "image":"img/prague_4.jpg",
        "caption":"Prague is my favorite city",
        "days":"4",
        "moves":"2",
        "countries":"Poland, Czechia, Germany",
        "towns":"Krakow, Prague, Dresden",
        "price":"180 Euro",
    },
    {
        "id":41,
        "image":"img/venice_1.jpg",
        "caption":"Venice and Verona",
        "days":"4",
        "moves":"2",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Verona",
        "price":"162 Euro",
    },
    {
        "id":42,
        "image":"img/normandy_1.jpg",
        "caption":"The Netherlands and Normandy",
        "days":"7",
        "moves":"2",
        "countries":"Germany, Netherlands, France",
        "towns":"Berlin, Amsterdam, Paris",
        "price":"345 Euro",
    },
    {
        "id":43,
        "image":"img/gdansk.jpg",
        "caption":"Polish jazz",
        "days":"4",
        "moves":"no",
        "countries":"Poland",
        "towns":"Lublin, Warsaw, Gdansk, Krakow",
        "price":"200 Euro",
    },
    {
        "id":44,
        "image":"img/munich_1.jpg",
        "caption":"Alpine pearls",
        "days":"6",
        "moves":"no",
        "countries":"Germany, Austria",
        "towns":"Munich, Salzburg, Hallstatt",
        "price":"300 Euro",
    },
    {
        "id":45,
        "image":"img/norway_3.jpg",
        "caption":"The three elements of Norway",
        "days":"8",
        "moves":"no",
        "countries":"Poland, Norway, Denmark",
        "towns":"Gdansk, Oslo, Copenhagen",
        "price":"630 Euro",
    },
    {
        "id":46,
        "image":"img/zakopane.jpg",
        "caption":"Morske Oko, Zakopane, Krakow",
        "days":"3",
        "moves":"no",
        "countries":"Poland",
        "towns":"Zakopane, Krakow",
        "price":"155 Euro",
    },
    {
        "id":47,
        "image":"img/athens_1.jpg",
        "caption":"Legends of ancient Greece",
        "days":"6",
        "moves":"2",
        "countries":"Greece, Romania",
        "towns":"Athens, Bucharest, Brasov",
        "price":"290 Euro",
    },
    {
        "id":48,
        "image":"img/copenhagen_2.jpg",
        "caption":"Secrets of the North",
        "days":"7",
        "moves":"no",
        "countries":"Sweden, Denmark, Germany",
        "towns":"Stockholm, Copenhagen, Hamburg",
        "price":"490 Euro",
    },
    {
        "id":49,
        "image":"img/paris_2.jpeg",
        "caption":"France and Switzerland",
        "days":"7",
        "moves":"no",
        "countries":"France, Switzerland",
        "towns":"Paris, Lucerne, Zurich",
        "price":"385 Euro",
    },
    {
        "id":50,
        "image":"img/karlovy_vary_2.jpg",
        "caption":"Czech fairy tales",
        "days":"6",
        "moves":"2",
        "countries":"Czechia",
        "towns":"Prague, Karlovy Vary",
        "price":"220 Euro",
    },
    {
        "id":51,
        "image":"img/castle_1.jpg",
        "caption":"Normandy and Mon Saint Michel",
        "days":"8",
        "moves":"no",
        "countries":"France",
        "towns":"Rouen, Dijon, Strasbourg",
        "price":"500 Euro",
    },
    {
        "id":52,
        "image":"img/hamburg_1.jpg",
        "caption":"Unforgettable vacation",
        "days":"6",
        "moves":"no",
        "countries":"Germany",
        "towns":"Berlin, Dresden, Hamburg",
        "price":"330 Euro",
    },
    {
        "id":53,
        "image":"img/budapest_2.jpg",
        "caption":"Your amazing weekend",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Hungary, Austria",
        "towns":"Krakow, Budapest, Vienna",
        "price":"235 Euro",
    },
    {
        "id":54,
        "image":"img/copenhagen_1.jpg",
        "caption":"Cities of the northern winds",
        "days":"10",
        "moves":"no",
        "countries":"Norway, Denmark, Sweden",
        "towns":"Oslo, Copenhagen, Stockholm",
        "price":"620 Euro",
    },
    {
        "id":55,
        "image":"img/bologna_1.jpg",
        "caption":"Amazing Italy",
        "days":"7",
        "moves":"no",
        "countries":"Italy",
        "towns":"Bologna, Venice, Florence, Rome",
        "price":"399 Euro",
    },
    {
        "id":56,
        "image":"img/prague_1.jpg",
        "caption":"My fabulous Prague",
        "days":"4",
        "moves":"2",
        "countries":"Poland, Czechia",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"145 Euro",
    },
    {
        "id":57,
        "image":"img/vienna_1.jpg",
        "caption":"Budapest and Vienna",
        "days":"4",
        "moves":"2",
        "countries":"Hungary, Austria",
        "towns":"Budapest, Vienna",
        "price":"112 Euro",
    },
    {
        "id":59,
        "image":"img/park_1.jpg",
        "caption":"Amsterdam and Keukenhof Park",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Germany, Netherlands",
        "towns":"Wroclaw, Dresden, Amsterdam",
        "price":"252 Euro",
    },
    {
        "id":60,
        "image":"img/istanbul_1.jpg",
        "caption":"From Istanbul to Athens",
        "days":"6",
        "moves":"2",
        "countries":"Greece, Turkey, Romania",
        "towns":"Athens, Istanbul, Bucharest",
        "price":"290 Euro",
    },
    {
        "id":61,
        "image":"img/locarno.jpg",
        "caption":"Italy and Switzerland",
        "days":"5",
        "moves":"2",
        "countries":"Poland, Switzerland, Italy",
        "towns":"Krakow, Locarno, Milan",
        "price":"267 Euro",
    },
    {
        "id":62,
        "image":"img/dresden_2.jpg",
        "caption":"Czech pearls",
        "days":"5",
        "moves":"no",
        "countries":"Germany, Czechia",
        "towns":"Dresden, Prague, Karlovy Vary",
        "price":"330 Euro",
    },
    {
        "id":63,
        "image":"img/milan_1.jpg",
        "caption":"Northern diamonds of Italy",
        "days":"6",
        "moves":"no",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Milan, Turin",
        "price":"338 Euro",
    },
    {
        "id":64,
        "image":"img/norway_4.jpg",
        "caption":"At the call of the heart... Norway",
        "days":"10",
        "moves":"no",
        "countries":"Poland, Norway, Denmark",
        "towns":"Gdansk, Oslo, Copenhagen",
        "price":"790 Euro",
    },
    {
        "id":65,
        "image":"img/paris_5.jpg",
        "caption":"Paris and Berlin",
        "days":"5",
        "moves":"2",
        "countries":"Germany, France, Czechia",
        "towns":"Berlin, Paris, Prague",
        "price":"250 Euro",
    },
    {
        "id":66,
        "image":"img/karlovy_vary_1.jpg",
        "caption":"The weekend of your dreams",
        "days":"4",
        "moves":"1",
        "countries":"Poland, Czechia",
        "towns":"Krakow, Prague, Karlovy Vary",
        "price":"150 Euro",
    },
    {
        "id":67,
        "image":"img/residense.jpg",
        "caption":"Journey to Santa's world",
        "days":"9",
        "moves":"no",
        "countries":"Estonia, Finland, Sweden",
        "towns":"Tallinn, Helsinki, Stockholm",
        "price":"750 Euro",
    },
    {
        "id":68,
        "image":"img/zurich_3.jpg",
        "caption":"Paris and Zurich",
        "days":"6",
        "moves":"no",
        "countries":"France, Switzerland, Czechia",
        "towns":"Paris, Zurich, Prague",
        "price":"390 Euro",
    },
    {
        "id":69,
        "image":"img/timisoara.jpg",
        "caption":"A trip through the Balkans",
        "days":"6",
        "moves":"2",
        "countries":"Croatia, Montenegro, Romania",
        "towns":"Dubrovnik, Budva, Timisoara",
        "price":"290 Euro",
    },
    {
        "id":70,
        "image":"img/amsterdam_2.jpg",
        "caption":"Unforgettable Amsterdam",
        "days":"5",
        "moves":"2",
        "countries":"Germany, Netherlands, Czechia",
        "towns":"Berlin, Amsterdam, Prague",
        "price":"212 Euro",
    },
    {
        "id":72,
        "image":"img/vienna_2.jpg",
        "caption":"Weekend in Europe",
        "days":"5",
        "moves":"no",
        "countries":"Poland,Czechia, Hungary",
        "towns":"Krakow, Prague, Budapest",
        "price":"250 Euro",
    }
]