let tours = [
    {
        "id":1,
        "image":"img/amsterdam_2.jpg",
        "caption":"Unforgettable Amsterdam",
        "days":"5",
        "moves":"2",
        "countries":"Germany, Netherlands, Czechia",
        "towns":"Berlin, Amsterdam, Prague",
        "price":"212 Euro",
    },
    {
        "id":2,
        "image":"img/park_1.jpg",
        "caption":"Amsterdam and Keukenhof Park",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Germany, Netherlands",
        "towns":"Wroclaw, Dresden, Amsterdam",
        "price":"252 Euro",
    },
    {
        "id":3,
        "image":"img/dresden_1.jpg",
        "caption":"Vacation in the Netherlands",
        "days":"7",
        "moves":"no",
        "countries":"Germany, Netherlands, Germany",
        "towns":"Dresden, Amsterdam, Cologne",
        "price":"375 Euro",
    },
    {
        "id":4,
        "image":"img/paris_1.jpg",
        "caption":"Paris and Amsterdam",
        "days":"7",
        "moves":"no",
        "countries":"Germany, Netherlands, France",
        "towns":"Berlin, Amsterdam, Paris",
        "price":"427 Euro",
    },
    {
        "id":5,
        "image":"img/normandy_1.jpg",
        "caption":"The Netherlands and Normandy",
        "days":"7",
        "moves":"2",
        "countries":"Germany, Netherlands, France",
        "towns":"Berlin, Amsterdam, Paris",
        "price":"345 Euro",
    },
    {
        "id":6,
        "image":"img/warsaw_1.jpg",
        "caption":"Fairytale cities",
        "days":"8",
        "moves":"no",
        "countries":"Poland, Netherlands, France",
        "towns":"Warsaw, Amsterdam, Paris",
        "price":"460 Euro",
    }
]