let tours = [
    {
        "id":1,
        "image":"img/vienna_1.jpg",
        "caption":"Budapest and Vienna",
        "days":"4",
        "moves":"2",
        "countries":"Hungary, Austria",
        "towns":"Budapest, Vienna",
        "price":"112 Euro",
    },
    {
        "id":2,
        "image":"img/budapest_2.jpg",
        "caption":"Your amazing weekend",
        "days":"5",
        "moves":"no",
        "countries":"Poland, Hungary, Austria",
        "towns":"Krakow, Budapest, Vienna",
        "price":"235 Euro",
    },
    {
        "id":3,
        "image":"img/eger_1.jpg",
        "caption":"Austrian hit + Budapest",
        "days":"4",
        "moves":"2",
        "countries":"Austria, Hungary",
        "towns":"Vienna, Budapest, Eger",
        "price":"156 Euro",
    },
    {
        "id":4,
        "image":"img/prague_2.jpg",
        "caption":"Weekend in Europe",
        "days":"4",
        "moves":"1",
        "countries":"Poland, Czechia, Austria, Hungary",
        "towns":"Krakow, Prague, Vienna, Budapest",
        "price":"168 Euro",
    },
    {
        "id":5,
        "image":"img/zurich_1.jpg",
        "caption":"Beautiful days in Switzerland",
        "days":"5",
        "moves":"2",
        "countries":"Hungary, Autria, Switzerland",
        "towns":"Budapest, Vienna, Zurich",
        "price":"250 Euro",
    },
    {
        "id":6,
        "image":"img/ljubljana_1.jpg",
        "caption":"Slovenia and Hungary",
        "days":"5",
        "moves":"2",
        "countries":"Hungary, Slovenia",
        "towns":"Budapest, Ljubljana",
        "price":"250 Euro",
    }

]
