let tours = [
    {
        "id":1,
        "image":"img/paris_3.jpg",
        "caption":"Paris - the city of love",
        "days":"6",
        "moves":"2",
        "towns":"Krakow, Paris, Prague",
        "price":"295 Euro",
    },
    {
        "id":2,
        "image":"img/paris_4.jpg",
        "caption":"Wonderful vacion in France",
        "days":"7",
        "moves":"2",
        "towns":"Berlin, Paris, Prague",
        "price":"305 Euro",
    },
    {
        "id":3,
        "image":"img/luxembourg_1.jpg",
        "caption":"Paris and Luxembourg",
        "days":"6",
        "moves":"no",
        "towns":"Krakow, Paris, Luxembourg",
        "price":"380 Euro",
    },
    {
        "id":4,
        "image":"img/rouen_1.jpg",
        "caption":"Paris and Normandy",
        "days":"7",
        "moves":"no",
        "towns":"Paris, Rouen, Krakow",
        "price":"410 Euro",
    },
    {
        "id":5,
        "image":"img/castle_1.jpg",
        "caption":"Normandy and Mon Saint Michel",
        "days":"8",
        "moves":"no",
        "towns":"Rouen, Dijon, Strasbourg",
        "price":"500 Euro",
    },
    {
        "id":6,
        "image":"img/switzerland_3.jpg",
        "caption":"France and Switzerland",
        "days":"7",
        "moves":"no",
        "towns":"Paris, Dresden, Zurich",
        "price":"500 Euro",
    }
]