let tours = [
    {
        "id":1,
        "image":"img/rome_1.jpg",
        "caption":"Weekend in Italy",
        "days":"5",
        "moves":"2",
        "countries":"Italy",
        "towns":"Venice, Florence, Rome",
        "price":"237 Euro",
    },
    {
        "id":2,
        "image":"img/rome_2.jpg",
        "caption":"Rome: the Eternal city",
        "days":"6",
        "moves":"no",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Florence, Rome",
        "price":"355 Euro",
    },
    {
        "id":3,
        "image":"img/venice_1.jpg",
        "caption":"Venice and Verona",
        "days":"4",
        "moves":"2",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Verona",
        "price":"162 Euro",
    },
    {
        "id":4,
        "image":"img/italy_1.jpg",
        "caption":"Weekend in Liguria",
        "days":"5",
        "moves":"2",
        "countries":"Italy",
        "towns":"Genoa, Florence, Cinque Terre",
        "price":"221 Euro",
    },
    {
        "id":5,
        "image":"img/bologna_1.jpg",
        "caption":"Amazing Italy",
        "days":"7",
        "moves":"no",
        "countries":"Italy",
        "towns":"Bologna, Venice, Florence, Rome",
        "price":"399 Euro",
    },
    {
        "id":6,
        "image":"img/milan_1.jpg",
        "caption":"Northern diamonds of Italy",
        "days":"6",
        "moves":"no",
        "countries":"Hungary, Italy",
        "towns":"Budapest, Venice, Milan, Turin",
        "price":"338 Euro",
    }
]