let tours = [
    {
        "id":1,
        "image":"img/flam_1.jpg",
        "caption":"Getting to know Norway",
        "days":"7",
        "moves":"2",
        "countries":"Denmark, Norway",
        "towns":"Copenhagen, Flam, Bergen",
        "price":"410 Euro",
    },
    {
        "id":2,
        "image":"img/oslo_1.jpg",
        "caption":"Land of fjords and glaciers",
        "days":"7",
        "moves":"no",
        "countries":"Denmark, Norway",
        "towns":"Copenhagen, Oslo, Bergen",
        "price":"510 Euro",
    },
    {
        "id":3,
        "image":"img/stockholm_1.jpg",
        "caption":"Stockholm and Oslo",
        "days":"7",
        "moves":"no",
        "countries":"Sweden, Norway, Latvia",
        "towns":"Stockholm, Oslo, Riga",
        "price":"450 Euro",
    },
    {
        "id":4,
        "image":"img/norway_3.jpg",
        "caption":"The three elements of Norway",
        "days":"8",
        "moves":"no",
        "countries":"Poland, Norway, Denmark",
        "towns":"Gdansk, Oslo, Copenhagen",
        "price":"630 Euro",
    },
    {
        "id":5,
        "image":"img/copenhagen_1.jpg",
        "caption":"Cities of the northern winds",
        "days":"10",
        "moves":"no",
        "countries":"Norway, Denmark, Sweden",
        "towns":"Oslo, Copenhagen, Stockholm",
        "price":"620 Euro",
    },
    {
        "id":6,
        "image":"img/norway_4.jpg",
        "caption":"At the call of the heart... Norway",
        "days":"10",
        "moves":"no",
        "countries":"Poland, Norway, Denmark",
        "towns":"Gdansk, Oslo, Copenhagen",
        "price":"790 Euro",
    }
]